version: '3.4'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27018:27017
   
  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: voltz
      ME_CONFIG_BASICAUTH_PASSWORD: voltz123
      ME_CONFIG_MONGODB_PORT: 27018
    depends_on:
      - mongo
   
  bookstore:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
      
networks:
  mongo-compose-network:
    driver: bridge

  